# Generated by Django 4.2.26 on 2025-12-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspContainerEspModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'esp_container',
            },
        ),
        migrations.CreateModel(
            name='SensorDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_temp', models.IntegerField(default=0)),
                ('current_air_humidity', models.IntegerField(default=0)),
                ('current_ground_humidity', models.IntegerField(default=0)),
                ('current_light', models.BooleanField(default=False)),
                ('current_meta_params', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='UserParamsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_temp', models.IntegerField(default=0)),
                ('need_air_humidity', models.IntegerField(default=0)),
                ('need_ground_humidity', models.IntegerField(default=0)),
                ('need_light', models.BooleanField(default=False)),
                ('need_meta_params', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'user_params',
            },
        ),
    ]
