# Generated by Django 4.2.26 on 2025-11-30 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0002_containermodel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePanelEspModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_temp', models.IntegerField(default=0)),
                ('need_air_humidity', models.IntegerField(default=0)),
                ('need_ground_humidity', models.IntegerField(default=0)),
                ('need_light', models.BooleanField(default=False)),
                ('need_meta_params', models.JSONField(default=dict)),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esp', to='container.containermodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'esp_container',
            },
        ),
    ]
