# Generated by Django 4.2.26 on 2025-12-01 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esp', '0001_initial'),
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espcontainerespmodel',
            name='plant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esp', to='plant.plantmodel'),
        ),
        migrations.AddField(
            model_name='espcontainerespmodel',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esp', to='esp.sensordevicemodel'),
        ),
        migrations.AddField(
            model_name='espcontainerespmodel',
            name='user_params',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esp', to='esp.userparamsmodel'),
        ),
    ]
