# Generated by Django 4.2.26 on 2025-12-01 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CharacterPlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_deviation', models.IntegerField(default=5)),
                ('temp', models.IntegerField(default=24)),
                ('air_humidity', models.IntegerField(default=60)),
                ('ground_humidity', models.IntegerField(default=60)),
                ('light', models.IntegerField(default=8)),
                ('is_user_create', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'character_plant',
            },
        ),
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plant', to='plant.categorymodel')),
                ('character_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='plant.characterplantmodel')),
            ],
            options={
                'db_table': 'plant',
            },
        ),
    ]
