# Generated by Django 4.2.26 on 2025-11-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantmodel',
            name='is_user_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
