# Generated by Django 4.2.26 on 2025-11-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_plantmodel_is_user_create_alter_plantmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plant', to='plant.categorymodel'),
        ),
    ]
