# Generated by Django 4.2.26 on 2025-11-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_plantmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterplantmodel',
            name='is_user_create',
            field=models.BooleanField(default=True),
        ),
    ]
