# Generated by Django 4.2.26 on 2025-11-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_characterplantmodel_is_user_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
