# Generated by Django 4.2.26 on 2025-11-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_alter_categorymodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plant', to='plant.categorymodel'),
        ),
    ]
