# Generated by Django 4.2.26 on 2025-11-30 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant', '0006_alter_plantmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantmodel',
            old_name='is_user_create',
            new_name='is_default',
        ),
        migrations.AddField(
            model_name='plantmodel',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='plant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
