# Generated by Django 4.2.26 on 2025-11-30 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0006_alter_plantmodel_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_temp', models.IntegerField(default=0)),
                ('current_air_humidity', models.IntegerField(default=0)),
                ('current_ground_humidity', models.IntegerField(default=0)),
                ('current_light', models.BooleanField(default=False)),
                ('current_meta_params', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='plant.plantmodel')),
            ],
            options={
                'db_table': 'container',
            },
        ),
    ]
