# Generated by Django 4.2.26 on 2025-11-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containermodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
